### ISSUE TITLE
mibitof example in vignette prohibitively slow --

### ISSUE THREAD

**Issue by vjcitn** [HelenaLC/SpatialData#67]
https://github.com/HelenaLC/SpatialData/blob/644483b4c5fed2d61ac0c52e733cc8b0fb36dd68/vignettes/SpatialData.Rmd#L102

could we use a static screenshot and add computations to longtests if there are risks?

**Comment by HelenaLC** [comment]
significant speed up by using `annotation_raster` instead of `geom_tile` (#71)
