### ISSUE TITLE
Multichannel support

### ISSUE THREAD

**Issue by vjcitn** [HelenaLC/SpatialData#85]
```
> dir.create("/tmp/defmm")
> unzip_spd_demo("mcmicro.io", dest="/tmp/defmm") -> mm
returning path to cached zip
> mcm = readSpatialData(mm)
> mcm
class: SpatialData
- images(1):
  - exemplar-001_image (12,3139,2511)
- labels(2):
  - exemplar-001_cell (3139,2511)
  - exemplar-001_nuclei (3139,2511)
- points(0):
- shapes(0):
- tables(2):
  - exemplar-001--ilastik_cell (12,11607)
  - exemplar-001--unmicst_cell (12,11170)
coordinate systems:
- global(3): exemplar-001_image exemplar-001_cell exemplar-001_nuclei
> plotSpatialData() + plotImage(mcm)
Error in (function (red, green, blue, alpha, names = NULL, maxColorValue = 1)  : 
  unused arguments (0, 0, 0, 0, 0, 0)

Enter a frame number, or 0 to exit   

1: plotImage(mcm)
2: plotImage(mcm)
3: .local(x, ...)
4: .df_i(y, k)
5: apply(a, c(2, 3), function(.) do.call(rgb, as.list(.)))
6: FUN(newX[, i], ...)
7: do.call(rgb, as.list(.))
```

**Comment by vjcitn** [comment]
same problem with steinbock example but different unused arguments

**Comment by Artur-man** [comment]
This image has 12 channels, which are different from the examples we had during the workshop. Perhaps a slight modification to better control image channels should handle this

**Comment by Artur-man** [comment]
@HelenaLC if its ok i wanna look into this quick

**Comment by Artur-man** [comment]
Here the users have a higher level of control over how channels should be combined to be visualized

<img width="802" alt="Screenshot 2024-11-17 at 14 53 55" src="https://github.com/user-attachments/assets/bcb33b37-7a48-43c6-b9e7-ccb1337ffa13">

**Comment by Artur-man** [comment]
Here is a good example, the channel names are explicitly defined and specifically rgb when it is, @HelenaLC perhaps to come up with a `is.rgb` function to check how channels should be rasterized before passing to `annotation_raster` ? 

We can then pick the first channel as example (if not rgb), then discuss how to combine channels ? I have some experience in this from voltron as well, might look.
https://github.com/BIMSBbioinfo/VoltRon/blob/c75edad9e7eee1e7de28527efaf6dd19650ddfee/R/image.R#L1116-L1128

MERFISH: 

```
> z$images$rasterized@meta[[2]]
$channels
  label
1     0
```

VisiumHD: 

```
y$images$Visium_HD_Mouse_Small_Intestine_full_image@meta[[2]]
```

Mcmicro:

```
> x$images$`exemplar-001_image`@meta[[2]]
$channels
   label
1  DNA_6
2  ELANE
3   CD57
4   CD45
5  DNA_7
6  CD11B
7    SMA
8   CD16
9  DNA_8
10  ECAD
11 FOXP3
12  NCAM
```

**Comment by Artur-man** [comment]
```
#' @importFrom methods as
#' @importFrom abind abind
#' @importFrom grDevices rgb
#' @importFrom DelayedArray realize
.df_i <- \(x, k=NULL) {
    a <- .get_plot_data(x, k)
    if (max(a) > 1) a <- a/255
```

```
Browse[2]> max(a)
[1] 65535
```

We also have to take into account the numpy like array numeric formats .... here this integer array is probably uint16, hence maximum can exceed 255. This can be parsed from the ZarrArray i think but not implemented by Mike yet, perhaps we can ping him quickly ? I now that it exists in HDF5Array (I think).

**Comment by Artur-man** [comment]
https://github.com/HelenaLC/SpatialData/blob/9381d708ad4deea4e237bdc50aaf6c522738e845/R/plot.R#L48-L58

**Comment by Artur-man** [comment]
@melonora @LucaMarconato, is there a particular image merging method that you prioritize in spatialdata-plot ?
https://usage.imagemagick.org/layers/#evaluate-sequence

<img width="642" alt="Screenshot 2024-11-21 at 21 35 35" src="https://github.com/user-attachments/assets/c1ab8f0c-3323-4679-be58-026680ded250">

**Comment by LucaMarconato** [comment]
> @melonora @LucaMarconato, is there a particular image merging method that you prioritize in spatialdata-plot ?
> [usage.imagemagick.org/layers#evaluate-sequence](https://usage.imagemagick.org/layers/#evaluate-sequence)

I forward the question to @timtreis and @Sonja-Stockhaus 😊

**Comment by timtreis** [comment]
Just dug through the code and I'm actually not fully sure if it makes 100% sense but we haven't gotten bug reports on that yet IIRC 😅 

For 1 or 3 channels, we delegate to `matplotlib.imshow` which states

> 
> There are two common representations for RGB images with an alpha channel:
> 
> - Straight (unassociated) alpha: R, G, and B channels represent the color of the pixel, disregarding its opacity.
> - Premultiplied (associated) alpha: R, G, and B channels represent the color of the pixel, adjusted for its opacity by multiplication.
> 
> [imshow](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html#matplotlib.pyplot.imshow) expects RGB images adopting the straight (unassociated) alpha representation.

If we have more than 3 channels, we try to match them to potential user-defined cmaps or colors and then sum the RGB values for those channels up --> https://github.com/scverse/spatialdata-plot/blob/12f490d0d16c9f1cf48e5373d1a39c815b5b98ed/src/spatialdata_plot/pl/render.py#L800

**Comment by Artur-man** [comment]
Thanks for checking @timtreis. I think we have decided to go with the summation approach for combining mIF channels too, just wanted to confirm by you. 

However, you should still be summing RGBs of antibody channels even if the number of channels are say two right ? 
e.g. ["DAPI", "CD45"] ["grey", "yellow"]

Here is the current implementation in `SpatialData.plot`:
https://github.com/HelenaLC/SpatialData.plot/blob/91acefc6f18c436db879b7684bde8d61fb590487/R/plotImage.R#L75-L103

We haven't really finalised the use of contrast parameters though.
