### ISSUE TITLE
various problems with linux deployment

### ISSUE THREAD

**Issue by vjcitn** [HelenaLC/SpatialData#91]
Not sure if anyone is trying this out on linux.  I am trying `example(use_sdio)` on the current checkout.  On a 22.04 machine in NSF cloud I hit

<img width="1029" alt="geos" src="https://github.com/user-attachments/assets/a1014ea9-e021-4369-b160-e2fcc9847244">

On AnVIL in a custom container,

```
Error in py_module_import(module, convert = convert) : 
  ImportError: /usr/lib/x86_64-linux-gnu/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /home/rstudio/.cache/R/basilisk/1.18.0/SpatialData/0.99.16/anndata_env/lib/python3.10/site-packages/pyarrow/../../.././././libs2n.so.1)
Run `reticulate::py_last_error()` for details.
```
I will try to smoke these out.  Some detailed pinning for basilisk, and maybe some OS checks/runtime specs will be needed.

**Comment by vjcitn** [comment]
update: 
```
.env <- BasiliskEnvironment(
    pkgname="SpatialData", envname="anndata_env",
    pip = c("spatialdata==0.2.5", "spatialdata-io==0.1.5"),
    packages=c("anndata==0.9.1", "zarr==2.14.2"))
```
seems to permit solution for use_sdio on both linux and mac, testing and will PR soon.

**Comment by HelenaLC** [comment]
Thanks Vince. Anything no python-related (eg vignette) I can look into.
