### ISSUE TITLE
vignette blocker

### ISSUE THREAD

**Issue by vjcitn** [HelenaLC/SpatialData#95]
I don't understand how action is passing but I am hitting

```
* creating vignettes ... ERROR
--- re-building ‘SpatialData.Rmd’ using rmarkdown

Quitting from lines 94-114 [tbl] (SpatialData.Rmd)
Error: processing vignette 'SpatialData.Rmd' failed with diagnostics:
error in evaluating the argument 'j' in selecting a method for function 'element': no 'table' found for 'i'
--- failed re-building ‘SpatialData.Rmd’

SUMMARY: processing the following file failed:
  ‘SpatialData.Rmd’
```

**Comment by HelenaLC** [comment]
Assuming you redoced and reinstalled, I don't know... I'll try to split off part of the package tomorrow, which should downsize/clean up things a little. Let's see from there.

**Comment by vjcitn** [comment]
occurs with a completely fresh clone....

**Comment by vjcitn** [comment]
will try a different machine

**Comment by vjcitn** [comment]
ny error

**Comment by vjcitn** [comment]
The issue was an obsolete version of anndataR.  Once this was installed with the right ref, I could compute the vignette.
